-- Expedit ToolManager · demandes d'achat avec validation administrateur
-- Exécuter une fois dans Supabase > SQL Editor.

create table if not exists public.toolmanager_achat_tickets (
  id bigint generated by default as identity primary key,
  workspace_key text not null default 'expedit',
  mould_id text,
  project_id text,
  repair_id text,
  component text not null,
  quantity numeric not null default 1,
  material text,
  heat_treated boolean not null default false,
  description text,
  requester_id uuid not null references auth.users(id) on delete cascade,
  requester_name text not null,
  requester_email text,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  purchase_id text,
  created_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by uuid references auth.users(id)
);

alter table public.toolmanager_achat_tickets enable row level security;
grant select, insert, update, delete on public.toolmanager_achat_tickets to authenticated;
grant usage, select on sequence public.toolmanager_achat_tickets_id_seq to authenticated;

drop policy if exists "members can read achat tickets" on public.toolmanager_achat_tickets;
create policy "members can read achat tickets"
on public.toolmanager_achat_tickets for select to authenticated
using (
  workspace_key = 'expedit'
  and exists (
    select 1 from public.toolmanager_members member
    where member.user_id = (select auth.uid()) and member.active = true
  )
  and (
    requester_id = (select auth.uid())
    or exists (
      select 1 from public.toolmanager_members member
      where member.user_id = (select auth.uid())
        and member.active = true and member.role = 'admin'
    )
  )
);

drop policy if exists "members can create achat tickets" on public.toolmanager_achat_tickets;
create policy "members can create achat tickets"
on public.toolmanager_achat_tickets for insert to authenticated
with check (
  workspace_key = 'expedit'
  and requester_id = (select auth.uid())
  and status = 'pending'
  and exists (
    select 1 from public.toolmanager_members member
    where member.user_id = (select auth.uid()) and member.active = true
  )
);

drop policy if exists "admins can review achat tickets" on public.toolmanager_achat_tickets;
create policy "admins can review achat tickets"
on public.toolmanager_achat_tickets for update to authenticated
using (
  workspace_key = 'expedit'
  and exists (
    select 1 from public.toolmanager_members member
    where member.user_id = (select auth.uid())
      and member.active = true and member.role = 'admin'
  )
)
with check (
  workspace_key = 'expedit'
  and exists (
    select 1 from public.toolmanager_members member
    where member.user_id = (select auth.uid())
      and member.active = true and member.role = 'admin'
  )
);

drop policy if exists "admins can delete achat tickets" on public.toolmanager_achat_tickets;
create policy "admins can delete achat tickets"
on public.toolmanager_achat_tickets for delete to authenticated
using (
  workspace_key = 'expedit'
  and exists (
    select 1 from public.toolmanager_members member
    where member.user_id = (select auth.uid())
      and member.active = true and member.role = 'admin'
  )
);

create index if not exists toolmanager_achat_tickets_status_idx
on public.toolmanager_achat_tickets (workspace_key, status, created_at desc);
