const seed={
 projects:[
  {id:'P-24018',name:'Moule injection panneau de porte',customer:'AutoTech France',owner:'L. Martin',status:'Mise au point',progress:72,due:'2026-08-12',priority:'Haute'},
  {id:'P-24021',name:'Matrice d’emboutissage tambour',customer:'ÉlectroMaison',owner:'P. Bernard',status:'Usinage',progress:48,due:'2026-08-22',priority:'Moyenne'},
  {id:'P-24025',name:'Moule sous pression boîtier batterie',customer:'Nova Énergie',owner:'L. Martin',status:'Conception',progress:25,due:'2026-09-05',priority:'Haute'},
  {id:'P-24011',name:'Moule support tableau de bord',customer:'Mobilité Industrie',owner:'S. Leroy',status:'Terminé',progress:100,due:'2026-07-26',priority:'Basse'}],
 moulds:[
  {id:'MJ-0018',name:'Moule panneau de porte',type:'Injection',project:'P-24018',location:'Atelier A · Presse 3',cycles:12840,status:'Mise au point'},
  {id:'MJ-0021',name:'Matrice paroi de tambour',type:'Emboutissage',project:'P-24021',location:'Magasin · B12',cycles:8930,status:'À installer'},
  {id:'MJ-0011',name:'Moule support tableau de bord',type:'Injection',project:'P-24011',location:'Atelier A · Presse 6',cycles:35620,status:'En production'},
  {id:'MJ-0007',name:'Matrice capot avant',type:'Emboutissage',project:'P-23996',location:'Zone maintenance',cycles:41270,status:'En réparation'}],
 repairs:[
  {id:'WX-0082',mould:'MJ-0007',part:'Insert de poinçon',issue:'Ébréchure de l’arête',level:'Critique',owner:'L. Martin',status:'Achat requis',date:'2026-08-02',cost:6800},
  {id:'WX-0085',mould:'MJ-0018',part:'Tige d’éjection inclinée',issue:'Rayures de surface',level:'Modérée',owner:'P. Bernard',status:'En réparation',date:'2026-08-03',cost:1200},
  {id:'WX-0079',mould:'MJ-0011',part:'Broche d’éjection',issue:'Rupture par fatigue',level:'Modérée',owner:'S. Leroy',status:'Terminé',date:'2026-07-29',cost:460}],
 purchases:[
  {id:'CG-0116',part:'Insert de poinçon',drawing:'DRW-0007-03',supplier:'Précision Durand',qty:2,price:3400,status:'Consultation',eta:'2026-08-10'},
  {id:'CG-0113',part:'Tige d’éjection inclinée',drawing:'DRW-0018-12',supplier:'MecaMold',qty:4,price:300,status:'En fabrication',eta:'2026-08-08'},
  {id:'CG-0108',part:'Broche SKD61',drawing:'Pièce standard',supplier:'Fixations Loire',qty:20,price:23,status:'Reçu',eta:'2026-07-30'}]
};
let data=JSON.parse(localStorage.getItem('mouldOpsDataFr')||'null')||structuredClone(seed),view='dashboard',filter='Tous',selectedProjectId=null;
const $=s=>document.querySelector(s),content=$('#content');
const meta={dashboard:['Tableau de bord','Suivez vos moules et projets en temps réel','＋ Nouveau projet'],projects:['Gestion des projets','Du bureau d’études à la validation finale','＋ Nouveau projet'],moulds:['Parc de moules','Un historique clair pour chaque outillage','＋ Ajouter un moule'],repairs:['Pannes et réparations','Réagissez vite et réduisez les arrêts','＋ Signaler une panne'],purchases:['Suivi des achats','Du plan de refabrication à la livraison','＋ Nouvel achat'],reports:['Rapports statistiques','Transformez les données en actions','Exporter le rapport']};
const statusClass=s=>/Terminé|Reçu|production/.test(s)?'green':/réparation|Usinage|point|Consultation|fabrication/.test(s)?'orange':/Achat requis|Critique/.test(s)?'red':'blue';
const money=n=>Number(n||0).toLocaleString('fr-FR',{style:'currency',currency:'EUR',maximumFractionDigits:0});
const save=()=>{localStorage.setItem('mouldOpsDataFr',JSON.stringify(data));window.MoldCloud?.push(data)};
const badge=s=>`<span class="badge ${statusClass(s)}">${s}</span>`;
const progress=v=>`<div class="progress-label"><span>Avancement</span><b>${v}%</b></div><div class="progress"><span style="width:${v}%"></span></div>`;
function stats(){let a=data.projects.filter(x=>x.status!=='Terminé').length,b=data.moulds.filter(x=>x.status==='En production').length,c=data.repairs.filter(x=>x.status!=='Terminé').length,d=data.purchases.filter(x=>x.status!=='Reçu').length;return `<div class="stats">${[[a,'Projets en cours','3 nouveaux ce mois-ci','▦','green'],[b,'Moules en production','Fonctionnement normal','⬡','blue'],[c,'Pannes à traiter','1 dossier prioritaire','⚒','red'],[d,'Achats en cours','2 livraisons cette semaine','⌁','orange']].map((x,i)=>`<div class="stat-card" style="--accent:var(--${x[4]})"><div class="stat-top"><span>${x[1]}</span><span class="stat-icon">${x[3]}</span></div><div class="stat-value">${x[0]}</div><div class="stat-foot"><strong>${i===2?'!':'↗'}</strong> ${x[2]}</div></div>`).join('')}</div>`}
function dashboard(){return `<section class="hero"><div><h2>Bonjour, Louis</h2><p>Deux tâches arrivent à échéance. À traiter en priorité.</p></div><span class="date-chip">4 août 2026 · Mardi</span></section>${stats()}<div class="dashboard-grid"><section class="card"><div class="card-head"><h3>Projets prioritaires</h3><button class="link-btn" data-go="projects">Voir tout →</button></div><div class="project-list">${data.projects.slice(0,4).map(p=>`<div class="project-row"><div class="project-code">${p.id.slice(-2)}</div><div><h4>${p.name}</h4><p>${p.id} · ${p.customer}</p></div><div>${progress(p.progress)}</div>${badge(p.status)}</div>`).join('')}</div></section><section class="card"><div class="card-head"><h3>Activité récente</h3><span class="sub">Aujourd’hui</span></div><div class="timeline"><div class="event" style="--dot:var(--red)"><h4>Anomalie de moule signalée</h4><p>Insert de poinçon ébréché sur la matrice de capot</p><time>14:26 · L. Martin</time></div><div class="event" style="--dot:var(--orange)"><h4>Statut d’achat mis à jour</h4><p>La tige d’éjection est entrée en fabrication</p><time>11:08 · P. Bernard</time></div><div class="event"><h4>Compte-rendu de mise au point</h4><p>Troisième essai du moule panneau de porte terminé</p><time>09:42 · L. Martin</time></div><div class="event" style="--dot:var(--blue)"><h4>Composants reçus</h4><p>20 broches SKD61 contrôlées et stockées</p><time>Hier 16:30 · S. Leroy</time></div></div></section></div>`}
const defs={projects:{headers:['N° / Projet','Client','Responsable','Échéance','Avancement','Statut','Actions'],row:x=>`<td><button class="project-link" data-project="${x.id}"><b>${x.id}</b><span class="sub">${x.name}</span></button></td><td>${x.customer}</td><td>${x.owner}</td><td>${x.due}</td><td style="min-width:120px">${progress(x.progress)}</td><td>${badge(x.status)}</td>`},moulds:{headers:['N° / Moule','Type','Projet lié','Emplacement','Cycles','Statut','Actions'],row:x=>`<td><b>${x.id}</b><span class="sub">${x.name}</span></td><td>${x.type}</td><td>${x.project}</td><td>${x.location}</td><td>${Number(x.cycles).toLocaleString('fr-FR')}</td><td>${badge(x.status)}</td>`},repairs:{headers:['OT / Moule','Composant','Description','Gravité','Responsable','Date','Coût','Statut','Actions'],row:x=>`<td><b>${x.id}</b><span class="sub">${x.mould}</span></td><td>${x.part}</td><td>${x.issue}</td><td>${badge(x.level)}</td><td>${x.owner}</td><td>${x.date}</td><td>${money(x.cost)}</td><td>${badge(x.status)}</td>`},purchases:{headers:['Commande / Plan','Composant','Fournisseur','Qté','Prix unitaire','Livraison','Statut','Actions'],row:x=>`<td><b>${x.id}</b><span class="sub">${x.drawing}</span></td><td>${x.part}</td><td>${x.supplier}</td><td>${x.qty}</td><td>${money(x.price)}</td><td>${x.eta}</td><td>${badge(x.status)}</td>`}};
const options={projects:['Tous','Conception','Usinage','Mise au point','Terminé'],moulds:['Tous','À installer','Mise au point','En production','En réparation'],repairs:['Tous','Achat requis','En réparation','Terminé'],purchases:['Tous','Consultation','En fabrication','Reçu']};
function listPage(type){let arr=data[type],q=$('#globalSearch').value.trim().toLowerCase();if(q)arr=arr.filter(x=>Object.values(x).join(' ').toLowerCase().includes(q));if(filter!=='Tous')arr=arr.filter(x=>x.status===filter||x.level===filter);return `<div class="toolbar"><div class="filter-group">${options[type].map(x=>`<button class="filter ${filter===x?'active':''}" data-filter="${x}">${x}</button>`).join('')}</div><span class="sub">${arr.length} enregistrement${arr.length>1?'s':''}</span></div><div class="table-wrap"><table><thead><tr>${defs[type].headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${arr.length?arr.map(x=>`<tr>${defs[type].row(x)}<td class="row-actions"><button class="edit-btn" data-edit="${x.id}" data-type="${type}">Modifier</button><button data-delete="${x.id}" data-type="${type}">Supprimer</button></td></tr>`).join(''):`<tr><td colspan="10" class="empty">Aucun enregistrement correspondant</td></tr>`}</tbody></table></div>`}
function reports(){let total=data.repairs.reduce((s,x)=>s+Number(x.cost),0),purchase=data.purchases.reduce((s,x)=>s+Number(x.qty)*Number(x.price),0),months=[38,52,31,64,45,72];return `${stats()}<div class="report-grid"><section class="card"><div class="card-head"><div><h3>Coûts de réparation · 6 mois</h3><span class="sub">Indice mensuel</span></div><b>${money(total)}</b></div><div class="chart">${months.map((v,i)=>`<div class="bar-wrap"><div class="bar" data-value="${v}" style="height:${v}%"></div><div class="bar-label">${['Mars','Avr.','Mai','Juin','Juil.','Août'][i]}</div></div>`).join('')}</div></section><section class="card"><div class="card-head"><h3>Répartition des causes</h3></div><div class="donut-wrap"><div class="donut"></div><div class="legend">${[['Usure',42,'green'],['Rupture',26,'orange'],['Ébréchure',16,'red'],['Autres',16,'blue']].map(x=>`<div class="legend-item"><i style="background:var(--${x[2]})"></i><span>${x[0]}</span><b>${x[1]}%</b></div>`).join('')}</div></div></section></div><section class="card insight"><div><h3>Analyse</h3><p>Les poinçons et broches représentent <strong>58 %</strong> des dommages. Renforcez leur contrôle préventif et constituez un stock de sécurité.</p></div><div><span class="sub" style="color:#a9c1b5">Montant des achats</span><b style="font-size:20px">${money(purchase)}</b></div></section>`}
const addDays=(date,n)=>{let d=new Date(date||'2026-08-01');d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)};
function projectDetail(){let p=data.projects.find(x=>x.id===selectedProjectId);if(!p)return listPage('projects');let start=p.start||p.created||'2026-08-01',created=p.created||start;let stages=[['Analyse','analyseStart','analyseEnd',0,5],['Conception','designStart','designEnd',5,15],['Mise en plan','drawingStart','drawingEnd',15,23],['Usinage interne','internalStart','internalEnd',23,38],['Usinage fournisseur','supplierStart','supplierEnd',23,43],['Mise au point','tuningStart','tuningEnd',43,53],['Terminé','finishStart','finishEnd',53,55]];let current=Math.min(stages.length-1,Math.floor((Number(p.progress)||0)/15));return `<button class="back-btn" data-back-projects>← Retour aux projets</button><section class="project-hero card"><div><span class="eyebrow">${p.id}</span><h2>${p.name}</h2><p>${p.customer} · Responsable : ${p.owner}</p></div><div class="project-progress"><b>${p.progress}%</b><span>Avancement global</span></div></section><div class="detail-stats"><div class="card"><span>Créé le</span><b>${created}</b></div><div class="card"><span>Début du projet</span><b>${start}</b></div><div class="card"><span>Échéance finale</span><b>${p.due||'—'}</b></div><div class="card"><span>Statut actuel</span>${badge(p.status)}</div></div><section class="card workflow-card"><div class="card-head"><div><h3>Workflow du projet</h3><span class="sub">Planning prévisionnel par phase</span></div><button class="secondary" data-edit-project="${p.id}">Modifier le planning</button></div><div class="workflow">${stages.map((s,i)=>{let from=p[s[1]]||addDays(start,s[3]),to=p[s[2]]||addDays(start,s[4]),state=i<current?'done':i===current?'active':'pending';return `<div class="workflow-step ${state}"><div class="step-marker">${i<current?'✓':i+1}</div><div class="step-body"><div><h4>${s[0]}</h4><span>${state==='done'?'Terminée':state==='active'?'En cours':'À venir'}</span></div><p>${from} → ${to}</p><small>Durée prévue : ${Math.max(1,Math.round((new Date(to)-new Date(from))/86400000))} jours</small></div></div>`}).join('')}</div></section>`}
function render(){if(view==='projectDetail'){let p=data.projects.find(x=>x.id===selectedProjectId);$('#pageTitle').textContent=p?.name||'Projet';$('#pageDesc').textContent='Tableau de bord du projet';$('#mainAddBtn').textContent='Modifier le projet';content.innerHTML=projectDetail()}else{let m=meta[view];$('#pageTitle').textContent=m[0];$('#pageDesc').textContent=m[1];$('#mainAddBtn').textContent=m[2];content.innerHTML=view==='dashboard'?dashboard():view==='reports'?reports():listPage(view)}document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===(view==='projectDetail'?'projects':view)))}
const fields={projects:[['id','N° de projet','text','P-24026'],['name','Nom du projet','text','Ex. Moule de pare-chocs'],['customer','Client','text','Entreprise cliente'],['owner','Responsable','text','L. Martin'],['created','Date de création','date',''],['start','Début du projet','date',''],['due','Échéance finale','date',''],['status','Étape actuelle','select',['Analyse','Conception','Mise en plan','Usinage interne','Usinage fournisseur','Mise au point','Terminé']],['progress','Avancement (%)','number','0'],['priority','Priorité','select',['Haute','Moyenne','Basse']],['analyseStart','Analyse · début','date',''],['analyseEnd','Analyse · fin prévue','date',''],['designStart','Conception · début','date',''],['designEnd','Conception · fin prévue','date',''],['drawingStart','Mise en plan · début','date',''],['drawingEnd','Mise en plan · fin prévue','date',''],['internalStart','Usinage interne · début','date',''],['internalEnd','Usinage interne · fin prévue','date',''],['supplierStart','Usinage fournisseur · début','date',''],['supplierEnd','Usinage fournisseur · fin prévue','date',''],['tuningStart','Mise au point · début','date',''],['tuningEnd','Mise au point · fin prévue','date',''],['finishStart','Terminé · début','date',''],['finishEnd','Terminé · date prévue','date','']],moulds:[['id','N° du moule','text','MJ-0026'],['name','Nom du moule','text',''],['type','Type','select',['Injection','Emboutissage','Moulage sous pression','Autre']],['project','Projet lié','text','P-24026'],['location','Emplacement','text','Magasin'],['cycles','Nombre de cycles','number','0'],['status','Statut','select',['À installer','Mise au point','En production','En réparation']]],repairs:[['id','N° OT','text','WX-0086'],['mould','N° du moule','text','MJ-'],['part','Composant endommagé','text',''],['issue','Description de la panne','text',''],['level','Gravité','select',['Modérée','Critique']],['owner','Responsable','text','L. Martin'],['status','Statut','select',['Achat requis','En réparation','Terminé']],['date','Date','date',''],['cost','Coût estimé','number','0']],purchases:[['id','N° de commande','text','CG-0117'],['part','Composant','text',''],['drawing','N° du plan','text','DRW-'],['supplier','Fournisseur','text',''],['qty','Quantité','number','1'],['price','Prix unitaire','number','0'],['status','Statut','select',['Consultation','En fabrication','Reçu']],['eta','Livraison prévue','date','']]};
function openModal(type,record=null){let titles={projects:'Nouveau projet',moulds:'Ajouter un moule',repairs:'Signaler une panne',purchases:'Nouvel achat'},editTitles={projects:'Modifier le projet',moulds:'Modifier le moule',repairs:'Modifier la réparation',purchases:'Modifier l’achat'};$('#modalTitle').textContent=record?editTitles[type]:titles[type];$('#modalEyebrow').textContent=record?'MODIFICATION':'NOUVEAU';$('#entityForm').dataset.type=type;$('#entityForm').dataset.editId=record?.id||'';$('#formFields').innerHTML=fields[type].map(([key,label,t,opt])=>{let control=t==='select'?`<select name="${key}" required>${opt.map(v=>`<option>${v}</option>`).join('')}</select>`:`<input name="${key}" type="${t}" placeholder="${opt}" ${['id','name','part'].includes(key)?'required':''}>`;return `<div class="field"><label>${label}</label>${control}</div>`}).join('');if(record)Object.entries(record).forEach(([key,value])=>{let field=$('#entityForm').elements.namedItem(key);if(field)field.value=value});$('#modalBackdrop').classList.add('open')}
function closeModal(){$('#modalBackdrop').classList.remove('open');$('#entityForm').reset();$('#entityForm').dataset.editId=''}function toast(msg){let t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
$('#nav').onclick=e=>{let b=e.target.closest('[data-view]');if(b){view=b.dataset.view;filter='Tous';render()}};
content.onclick=e=>{let project=e.target.closest('[data-project]');if(project){selectedProjectId=project.dataset.project;view='projectDetail';render();return}let back=e.target.closest('[data-back-projects]');if(back){view='projects';selectedProjectId=null;render();return}let plan=e.target.closest('[data-edit-project]');if(plan){let record=data.projects.find(x=>x.id===plan.dataset.editProject);if(record)openModal('projects',record);return}let go=e.target.closest('[data-go]');if(go){view=go.dataset.go;filter='Tous';render()}let f=e.target.closest('[data-filter]');if(f){filter=f.dataset.filter;render()}let edit=e.target.closest('[data-edit]');if(edit){let record=data[edit.dataset.type].find(x=>x.id===edit.dataset.edit);if(record)openModal(edit.dataset.type,record)}let d=e.target.closest('[data-delete]');if(d&&confirm('Supprimer cet enregistrement ?')){data[d.dataset.type]=data[d.dataset.type].filter(x=>x.id!==d.dataset.delete);save();render();toast('Enregistrement supprimé')}};
$('#mainAddBtn').onclick=()=>{if(view==='reports'){window.print();return}if(view==='projectDetail'){let record=data.projects.find(x=>x.id===selectedProjectId);if(record)openModal('projects',record);return}openModal(view==='dashboard'?'projects':view)};$('#closeModal').onclick=$('#cancelModal').onclick=closeModal;$('#modalBackdrop').onclick=e=>{if(e.target.id==='modalBackdrop')closeModal()};
$('#entityForm').onsubmit=e=>{e.preventDefault();let type=e.target.dataset.type,editId=e.target.dataset.editId,returnToDetail=view==='projectDetail',obj=Object.fromEntries(new FormData(e.target));['progress','cycles','cost','qty','price'].forEach(k=>{if(k in obj)obj[k]=Number(obj[k]||0)});if(editId){let index=data[type].findIndex(x=>x.id===editId);if(index!==-1)data[type][index]={...data[type][index],...obj};if(type==='projects'&&selectedProjectId===editId)selectedProjectId=obj.id}else data[type].unshift(obj);save();closeModal();view=returnToDetail?'projectDetail':type;filter='Tous';render();toast(editId?'Modification enregistrée':'Enregistrement sauvegardé')};
$('#globalSearch').oninput=()=>{if(!['dashboard','reports'].includes(view))render()};$('#resetBtn').onclick=()=>{if(confirm('Restaurer les données de démonstration ?')){data=structuredClone(seed);save();render();toast('Données restaurées')}};
window.addEventListener('moldflow-cloud-ready',e=>{if(e.detail){data=e.detail;localStorage.setItem('mouldOpsDataFr',JSON.stringify(data))}else window.MoldCloud?.push(data);render();toast('Données cloud chargées')});
render();window.MoldCloud?.start(data).then(remote=>{if(remote&&remote!==data){data=remote;localStorage.setItem('mouldOpsDataFr',JSON.stringify(data));render()}});
