(function(root){
  const encoder=new TextEncoder();
  const xmlEscape=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[char]));
  const columnName=index=>{let name='';for(let n=index+1;n;n=Math.floor((n-1)/26))name=String.fromCharCode(65+(n-1)%26)+name;return name};
  const crcTable=(()=>{let table=new Uint32Array(256);for(let i=0;i<256;i++){let value=i;for(let bit=0;bit<8;bit++)value=value&1?0xedb88320^(value>>>1):value>>>1;table[i]=value>>>0}return table})();
  const crc32=bytes=>{let crc=0xffffffff;for(let i=0;i<bytes.length;i++)crc=crcTable[(crc^bytes[i])&255]^(crc>>>8);return (crc^0xffffffff)>>>0};
  const u16=(view,offset,value)=>view.setUint16(offset,value,true);
  const u32=(view,offset,value)=>view.setUint32(offset,value>>>0,true);
  function zip(entries){
    let localParts=[],centralParts=[],offset=0,now=new Date(),dosTime=(now.getHours()<<11)|(now.getMinutes()<<5)|(now.getSeconds()>>1),dosDate=((now.getFullYear()-1980)<<9)|((now.getMonth()+1)<<5)|now.getDate();
    entries.forEach(entry=>{
      let name=encoder.encode(entry.name),body=typeof entry.data==='string'?encoder.encode(entry.data):entry.data,crc=crc32(body),local=new Uint8Array(30+name.length),localView=new DataView(local.buffer);
      u32(localView,0,0x04034b50);u16(localView,4,20);u16(localView,6,0x0800);u16(localView,8,0);u16(localView,10,dosTime);u16(localView,12,dosDate);u32(localView,14,crc);u32(localView,18,body.length);u32(localView,22,body.length);u16(localView,26,name.length);u16(localView,28,0);local.set(name,30);localParts.push(local,body);
      let central=new Uint8Array(46+name.length),centralView=new DataView(central.buffer);u32(centralView,0,0x02014b50);u16(centralView,4,20);u16(centralView,6,20);u16(centralView,8,0x0800);u16(centralView,10,0);u16(centralView,12,dosTime);u16(centralView,14,dosDate);u32(centralView,16,crc);u32(centralView,20,body.length);u32(centralView,24,body.length);u16(centralView,28,name.length);u16(centralView,30,0);u16(centralView,32,0);u16(centralView,34,0);u16(centralView,36,0);u32(centralView,38,0);u32(centralView,42,offset);central.set(name,46);centralParts.push(central);offset+=local.length+body.length;
    });
    let centralSize=centralParts.reduce((sum,part)=>sum+part.length,0),end=new Uint8Array(22),endView=new DataView(end.buffer);u32(endView,0,0x06054b50);u16(endView,4,0);u16(endView,6,0);u16(endView,8,entries.length);u16(endView,10,entries.length);u32(endView,12,centralSize);u32(endView,16,offset);u16(endView,20,0);
    let result=new Uint8Array(offset+centralSize+end.length),cursor=0;[...localParts,...centralParts,end].forEach(part=>{result.set(part,cursor);cursor+=part.length});return result;
  }
  const textCell=(ref,value,style=0)=>`<c r="${ref}"${style?` s="${style}"`:''} t="inlineStr"><is><t xml:space="preserve">${xmlEscape(value)}</t></is></c>`;
  const numberCell=(ref,value,style=0)=>`<c r="${ref}"${style?` s="${style}"`:''}><v>${Number(value)||0}</v></c>`;
  function buildNomenclatureXlsx(rows){
    let headers=['N° d’achat','Nom de la pièce','Prix unitaire (€)','Quantité','Matière','Code article'],sheetRows=[];
    sheetRows.push(`<row r="1" ht="26" customHeight="1">${textCell('A1','Nomenclature des achats non payés',1)}</row>`);
    sheetRows.push(`<row r="2">${textCell('A2',`Généré le ${new Date().toLocaleDateString('fr-FR')}`)}</row>`);
    sheetRows.push('<row r="3"/>');
    sheetRows.push(`<row r="4" ht="22" customHeight="1">${headers.map((header,index)=>textCell(`${columnName(index)}4`,header,2)).join('')}</row>`);
    rows.forEach((row,index)=>{let r=index+5;sheetRows.push(`<row r="${r}">${textCell(`A${r}`,row.purchaseNumber)}${textCell(`B${r}`,row.partName)}${numberCell(`C${r}`,row.unitPrice,3)}${numberCell(`D${r}`,row.quantity,4)}${textCell(`E${r}`,row.material)}${textCell(`F${r}`,row.articleCode)}</row>`)});
    let lastRow=Math.max(4,rows.length+4),created=new Date().toISOString(),sheet=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView showGridLines="0" workbookViewId="0"><pane ySplit="4" topLeftCell="A5" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><sheetFormatPr defaultRowHeight="18"/><cols><col min="1" max="1" width="16" customWidth="1"/><col min="2" max="2" width="34" customWidth="1"/><col min="3" max="4" width="17" customWidth="1"/><col min="5" max="5" width="24" customWidth="1"/><col min="6" max="6" width="22" customWidth="1"/></cols><sheetData>${sheetRows.join('')}</sheetData><mergeCells count="1"><mergeCell ref="A1:F1"/></mergeCells><autoFilter ref="A4:F${lastRow}"/><pageMargins left="0.3" right="0.3" top="0.5" bottom="0.5" header="0.2" footer="0.2"/></worksheet>`;
    let styles=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><numFmts count="1"><numFmt numFmtId="164" formatCode="#,##0.00 [$€-fr-FR]"/></numFmts><fonts count="2"><font><sz val="10"/><name val="Arial"/></font><font><b/><color rgb="FFFFFFFF"/><sz val="10"/><name val="Arial"/></font></fonts><fills count="3"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF0B6547"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="2"><border><left/><right/><top/><bottom/><diagonal/></border><border><left/><right/><top/><bottom style="thin"><color rgb="FFD5E0DA"/></bottom><diagonal/></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="5"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0" applyAlignment="1"><alignment vertical="center"/></xf><xf numFmtId="0" fontId="1" fillId="2" borderId="0" xfId="0" applyFont="1" applyFill="1" applyAlignment="1"><alignment vertical="center"/></xf><xf numFmtId="0" fontId="1" fillId="2" borderId="1" xfId="0" applyFont="1" applyFill="1" applyBorder="1" applyAlignment="1"><alignment horizontal="center" vertical="center"/></xf><xf numFmtId="164" fontId="0" fillId="0" borderId="0" xfId="0" applyNumberFormat="1" applyAlignment="1"><alignment horizontal="right" vertical="center"/></xf><xf numFmtId="1" fontId="0" fillId="0" borderId="0" xfId="0" applyNumberFormat="1" applyAlignment="1"><alignment horizontal="right" vertical="center"/></xf></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>`;
    return zip([
      {name:'[Content_Types].xml',data:`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/><Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/><Override PartName="/docProps/app.xml" ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml"/></Types>`},
      {name:'_rels/.rels',data:`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="docProps/core.xml"/><Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties" Target="docProps/app.xml"/></Relationships>`},
      {name:'docProps/core.xml',data:`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><dc:creator>Expedit ToolManager</dc:creator><cp:lastModifiedBy>Expedit ToolManager</cp:lastModifiedBy><dcterms:created xsi:type="dcterms:W3CDTF">${created}</dcterms:created><dcterms:modified xsi:type="dcterms:W3CDTF">${created}</dcterms:modified></cp:coreProperties>`},
      {name:'docProps/app.xml',data:`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties" xmlns:vt="http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes"><Application>Expedit ToolManager</Application></Properties>`},
      {name:'xl/workbook.xml',data:`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Nomenclature" sheetId="1" r:id="rId1"/></sheets></workbook>`},
      {name:'xl/_rels/workbook.xml.rels',data:`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>`},
      {name:'xl/worksheets/sheet1.xml',data:sheet},
      {name:'xl/styles.xml',data:styles}
    ]);
  }
  function download(rows,filename){let bytes=buildNomenclatureXlsx(rows),blob=new Blob([bytes],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download=filename||`Nomenclature_achats_${new Date().toISOString().slice(0,10)}.xlsx`;document.body.appendChild(anchor);anchor.click();anchor.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
  let api={buildNomenclatureXlsx,download};if(typeof module!=='undefined'&&module.exports)module.exports=api;if(root)root.NomenclatureXlsx=api;
})(typeof window!=='undefined'?window:null);
