-- Expedit ToolManager · demandes de panne avec validation administrateur
-- Exécuter une fois dans Supabase > SQL Editor.

create table if not exists public.toolmanager_panne_tickets (
  id bigint generated by default as identity primary key,
  workspace_key text not null default 'expedit',
  mould_id text not null,
  description text not null,
  requester_id uuid not null references auth.users(id) on delete cascade,
  requester_name text not null,
  requester_email text,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  repair_id text,
  created_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by uuid references auth.users(id)
);

alter table public.toolmanager_panne_tickets enable row level security;
grant select, insert, update on public.toolmanager_panne_tickets to authenticated;
grant usage, select on sequence public.toolmanager_panne_tickets_id_seq to authenticated;

drop policy if exists "members can read panne tickets" on public.toolmanager_panne_tickets;
create policy "members can read panne tickets"
on public.toolmanager_panne_tickets for select to authenticated
using (
  workspace_key = 'expedit'
  and exists (
    select 1 from public.toolmanager_members member
    where member.user_id = (select auth.uid()) and member.active = true
  )
  and (
    requester_id = (select auth.uid())
    or exists (
      select 1 from public.toolmanager_members member
      where member.user_id = (select auth.uid())
        and member.active = true and member.role = 'admin'
    )
  )
);

drop policy if exists "members can create panne tickets" on public.toolmanager_panne_tickets;
create policy "members can create panne tickets"
on public.toolmanager_panne_tickets for insert to authenticated
with check (
  workspace_key = 'expedit'
  and requester_id = (select auth.uid())
  and status = 'pending'
  and exists (
    select 1 from public.toolmanager_members member
    where member.user_id = (select auth.uid()) and member.active = true
  )
);

drop policy if exists "admins can review panne tickets" on public.toolmanager_panne_tickets;
create policy "admins can review panne tickets"
on public.toolmanager_panne_tickets for update to authenticated
using (
  workspace_key = 'expedit'
  and exists (
    select 1 from public.toolmanager_members member
    where member.user_id = (select auth.uid())
      and member.active = true and member.role = 'admin'
  )
)
with check (
  workspace_key = 'expedit'
  and exists (
    select 1 from public.toolmanager_members member
    where member.user_id = (select auth.uid())
      and member.active = true and member.role = 'admin'
  )
);

create index if not exists toolmanager_panne_tickets_status_idx
on public.toolmanager_panne_tickets (workspace_key, status, created_at desc);
