-- Expedit ToolManager · tickets de création de projet presse
-- Exécuter une fois dans Supabase > SQL Editor.

create table if not exists public.toolmanager_press_project_tickets (
  id bigint generated by default as identity primary key,
  workspace_key text not null default 'expedit',
  project_name text not null,
  project_type text not null default 'Presse' check (project_type in ('Emboutissage', 'Sertissage', 'Presse')),
  customer text,
  description text not null,
  priority text not null default 'Normal' check (priority in ('Normal', 'Élevé', 'Urgent')),
  requester_id uuid not null references auth.users(id) on delete cascade,
  requester_name text not null,
  requester_email text,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  project_id text,
  created_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by uuid references auth.users(id)
);

alter table public.toolmanager_press_project_tickets
add column if not exists project_type text not null default 'Presse';
alter table public.toolmanager_press_project_tickets
drop constraint if exists toolmanager_press_project_tickets_project_type_check;
alter table public.toolmanager_press_project_tickets
add constraint toolmanager_press_project_tickets_project_type_check
check (project_type in ('Emboutissage', 'Sertissage', 'Presse'));

alter table public.toolmanager_press_project_tickets enable row level security;
grant select, insert, update, delete on public.toolmanager_press_project_tickets to authenticated;
grant usage, select on sequence public.toolmanager_press_project_tickets_id_seq to authenticated;

drop policy if exists "members can read press project tickets" on public.toolmanager_press_project_tickets;
create policy "members can read press project tickets" on public.toolmanager_press_project_tickets
for select to authenticated using (
  workspace_key = 'expedit'
  and exists (select 1 from public.toolmanager_members member where member.user_id = (select auth.uid()) and member.active = true)
  and (requester_id = (select auth.uid()) or exists (select 1 from public.toolmanager_members member where member.user_id = (select auth.uid()) and member.active = true and member.role = 'admin'))
);

drop policy if exists "members can create press project tickets" on public.toolmanager_press_project_tickets;
create policy "members can create press project tickets" on public.toolmanager_press_project_tickets
for insert to authenticated with check (
  workspace_key = 'expedit' and requester_id = (select auth.uid()) and status = 'pending'
  and exists (select 1 from public.toolmanager_members member where member.user_id = (select auth.uid()) and member.active = true)
);

drop policy if exists "requesters can update pending press project tickets" on public.toolmanager_press_project_tickets;
create policy "requesters can update pending press project tickets" on public.toolmanager_press_project_tickets
for update to authenticated
using (workspace_key = 'expedit' and requester_id = (select auth.uid()) and status = 'pending')
with check (
  workspace_key = 'expedit' and requester_id = (select auth.uid()) and status = 'pending'
  and exists (select 1 from public.toolmanager_members member where member.user_id = (select auth.uid()) and member.active = true)
);

drop policy if exists "admins can review press project tickets" on public.toolmanager_press_project_tickets;
create policy "admins can review press project tickets" on public.toolmanager_press_project_tickets
for update to authenticated
using (workspace_key = 'expedit' and exists (select 1 from public.toolmanager_members member where member.user_id = (select auth.uid()) and member.active = true and member.role = 'admin'))
with check (workspace_key = 'expedit' and exists (select 1 from public.toolmanager_members member where member.user_id = (select auth.uid()) and member.active = true and member.role = 'admin'));

drop policy if exists "admins can delete press project tickets" on public.toolmanager_press_project_tickets;
create policy "admins can delete press project tickets" on public.toolmanager_press_project_tickets
for delete to authenticated using (
  workspace_key = 'expedit'
  and exists (select 1 from public.toolmanager_members member where member.user_id = (select auth.uid()) and member.active = true and member.role = 'admin')
);

create index if not exists toolmanager_press_project_tickets_status_idx
on public.toolmanager_press_project_tickets (workspace_key, status, created_at desc);
