-- Messagerie privée interne : chaque message est visible uniquement par son expéditeur et son destinataire.
create table if not exists public.toolmanager_messages (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references auth.users(id) on delete cascade,
  sender_name text not null,
  recipient_id uuid not null references auth.users(id) on delete cascade,
  recipient_name text not null,
  body text not null check (char_length(body) between 1 and 2000),
  created_at timestamptz not null default now(),
  read_at timestamptz
);

alter table public.toolmanager_messages enable row level security;

-- Annuaire minimal, nécessaire pour choisir un destinataire (nom et identifiant uniquement).
drop policy if exists "members see active directory" on public.toolmanager_members;
create policy "members see active directory" on public.toolmanager_members
for select to authenticated
using (active = true);

drop policy if exists "participants read private messages" on public.toolmanager_messages;
create policy "participants read private messages" on public.toolmanager_messages
for select to authenticated
using (sender_id = auth.uid() or recipient_id = auth.uid());

drop policy if exists "members send private messages" on public.toolmanager_messages;
create policy "members send private messages" on public.toolmanager_messages
for insert to authenticated
with check (
  sender_id = auth.uid()
  and exists (select 1 from public.toolmanager_members member where member.user_id = auth.uid() and member.active = true)
  and exists (select 1 from public.toolmanager_members recipient where recipient.user_id = recipient_id and recipient.active = true)
);

drop policy if exists "recipients mark messages read" on public.toolmanager_messages;
create policy "recipients mark messages read" on public.toolmanager_messages
for update to authenticated
using (recipient_id = auth.uid())
with check (recipient_id = auth.uid());

drop policy if exists "participants delete private messages" on public.toolmanager_messages;
create policy "participants delete private messages" on public.toolmanager_messages
for delete to authenticated
using (sender_id = auth.uid() or recipient_id = auth.uid());
